### ISSUE TITLE
Add your profile

### ISSUE THREAD

**Issue by mrmorris** [rm-training/about-us#17]
<h3>Prakash</h3>

<ul>
 <li>Favorite city: SFO</li>
</ul>

**Comment by mrmorris** [comment]
Hey I fixed it here: https://github.com/rm-training/about-us/pull/18

**Comment by srawla3010** [comment]
fixed here https://github.com/rm-training/about-us/pull/25

**Comment by mrinalinikurup** [comment]
created Mrinalini's profile #24

**Comment by glyn34** [comment]
I fixed this in #26
